services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=integrador1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Integrador1/src/main/java/Repository/mysql/Integrador1.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
